#!/bin/bash
# Arturium Browser does not belong to the Chromium project and Google Inc
# Running Arturium Browser
HERE="$(dirname "$(readlink -f "${0}")")"
TITLE="$HERE/arturium-browser"
NULL=/dev/null
TEMP=/var/tmp

if [ $(id -u) != 0 ]; then
    echo -en "\E[31;1mThis command must be run as root\n"
    exit 1
fi

usage() {
  echo "$0 [--gdb] [--help] [--] [chrome-options]"
  echo
  echo "        --gdb                   Start within gdb"
  echo "        --help                  This help screen"
  echo "        --install-deps          Install dependencies"
}

check_executable() {
    out=$(file $(readlink -f $1) 2>$NULL)
    echo $out | grep -qs "ELF 32-bit LSB"
    if [ $? = 0 ]; then
        echo 32
        exit 1
    fi
    echo $out | grep -qs "ELF 64-bit LSB"
    if [ $? = 0 ]; then
        echo 64
        return
    fi
    if
    rm -rf "$HOME/.local/Arturium Browser/Cache" ; then
    rm -rf "$HOME/.local/Arturium Browser/GPUCache"
    rm -rf /tmp/* 2>$NULL
        return
    fi
    echo neither
}

deps() {
    cd "$HOME/.local/lib" 2>$NULL || mkdir "$TEMP/.lib" 2>$NULL || rm -rf "$TEMP/.lib" "$HOME/.local/.lib"
    ln -s "$TEMP/.lib" "$HOME/.local/lib" 2>$NULL
    python3 -m pip install -r "$HERE/requirements.txt" --user --no-warn-script-location
    cd "$HERE"
}

export LD_LIBRARY_PATH="$HERE:$HERE/lib:$HERE/lib.target${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

MISSING_LIBS=$(ldd "$HERE/$TITLE" 2>$NULL |grep "not found$" | cut -d" " -f 1|sed 's/\t//')
CHROME_ARCH=$(check_executable "$HERE/$TITLE")
uname -m | grep -qs x86_64
if [ $? = 1 ]; then
    LIBDIRS="/lib /lib32 /usr/lib /usr/lib32"
else
    LIBDIRS="/lib64 /lib /usr/lib64 /usr/lib"
fi

echo $MISSING_LIBS | grep -qs libbz2.so.1.0
if [ $? = 0 ]; then
    for dir in $LIBDIRS
    do
        if [ -e "$dir/libbz2.so.1" ]; then
            LIB_ARCH=$(check_executable "$dir/libbz2.so.1")
            if [ "$CHROME_ARCH" = "$LIB_ARCH" ]; then
                ln -snf "$dir/libbz2.so.1" "$HERE/libbz2.so.1.0"
                break;
            fi
        fi
    done
fi

for lib in libnspr4.so.0d libnss3.so.1d libnssutil3.so.1d libplc4.so.0d libplds4.so.0d libsmime3.so.1d libssl3.so.1d
do
    echo $MISSING_LIBS | grep -qs $lib
    if [ $? = 0 ]; then
        reallib=$(echo $lib | sed 's/\.[01]d$//')
        for dir in $LIBDIRS
        do
            if [ -e "$dir/$reallib" ]; then
                LIB_ARCH=$(check_executable "$dir/$reallib")
                if [ "$CHROME_ARCH" = "$LIB_ARCH" ]; then
                    ln -snf "$dir/$reallib" "$HERE/$lib"
                    break;
                fi
            fi
        done
    fi
done

CMD_PREFIX=
ARGS=()
while [ "$#" -gt 0 ]; do
    case "$1" in
    "--")
        shift
        break ;;
    "--gdb")
        CMD_PREFIX="/bin/gdb --args" ;;
    "--help")
        usage
        exit 0 ;;
    "--install-deps")
        deps
        exit 0 ;;
    *)
        ARGS=( "${ARGS[@]}" "$1" ) ;;
    esac
    shift
done
set -- "${ARGS[@]}" "$@"

exec $CMD_PREFIX "$TITLE" 2>$NULL || echo "Have you installed dependencies? Try $(echo $0) --install-deps"

exit $?
